hard_tabs = true
tab_spaces = 4
max_width = 120
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = true
fn_single_line = true
where_single_line = true
use_small_heuristics = "Max"
merge_derives = false
chain_width = 60
format_strings = true